# FOR DEVELOPMENT ONLY!

FROM node:16-alpine

# Create /web directory and set it as working directory
WORKDIR /web

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the app
COPY . ./

# Ensure port 3000 is accessible to our system
EXPOSE 3000

# Run 'npm run dev' 
CMD ["npm", "run", "dev"]